const propiedades = [
  {
    titulo: 'Casa en el Lago',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Privada Jesús Carranza 30',
    lat: 19.792709993101994,
    lng: -99.10513003315084,
    imagen: 'anuncio1.jpg',
    publicado: 1,
    precioId: 2,
    categoriaId: 2,
    usuarioId: 1,
    verificado: 1,
    estado: 'México',
    municipio: 'Zumpango',
    tipoId: 3
  },
  {
    titulo: 'Casa en la playa',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Calle Juan Escutia 11',
    lat: 19.10445000468961,
    lng: -96.11092001018623,
    imagen: 'anuncio2.jpg',
    publicado: 1,
    precioId: 3,
    categoriaId: 2,
    usuarioId: 1,
    verificado: 1,
    estado: 'Veracruz de Ignacio de la Llave',
    municipio: 'Boca del Río',
    tipoId: 1
  },
  {
    titulo: 'Casa con alberca',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Calle 16 de Septiembre 26',
    lat: 20.474210018512892,
    lng: -99.21625998765987,
    imagen: 'anuncio3.jpg',
    publicado: 1,
    precioId: 5,
    categoriaId: 2,
    usuarioId: 1,
    verificado: 0,
    estado: 'Hidalgo',
    municipio: 'Ixmiquilpan',
    tipoId: 2
  },
  {
    titulo: 'Casa con Garage',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Privada Jardines del Pedregal',
    lat: 20.3781000153991,
    lng: -99.97641998342071,
    imagen: 'anuncio4.jpg',
    publicado: 1,
    precioId: 2,
    categoriaId: 2,
    usuarioId: 1,
    verificado: 1,
    estado: 'Querétaro',
    municipio: 'San Juan del Río',
    tipoId: 1
  },
  {
    titulo: 'Casa Residencial',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Boulevard Hermanos Aldama',
    lat: 21.110110000000077,
    lng: -101.67689999999999,
    imagen: 'anuncio5.jpg',
    publicado: 1,
    precioId: 3,
    categoriaId: 2,
    usuarioId: 1,
    verificado: 0,
    estado: 'Guanajuato',
    municipio: 'León',
    tipoId: 3
  },
  {
    titulo: 'Casa Cerca de  la playa',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Calle La Aguada',
    lat: 21.536029224696122,
    lng: -105.28224147904196,
    imagen: 'anuncio6.jpg',
    publicado: 1,
    precioId: 3,
    categoriaId: 2,
    usuarioId: 2,
    verificado: 1,
    estado: 'Nayarit',
    municipio: 'San Blas',
    tipoId: 2
  },
  {
    titulo: 'Casa lujosa con piscina',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Avenida Hermenegildo Galeana',
    lat: 17.547288028927927,
    lng: -99.50347087622173,
    imagen: 'anuncio7.jpg',
    publicado: 1,
    precioId: 4,
    categoriaId: 2,
    usuarioId: 2,
    verificado: 0,
    estado: 'Guerrero',
    municipio: 'Chilpancingo de los Bravo',
    tipoId: 1
  },
  {
    titulo: 'Departamento de lujo',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Calle Porfirio Díaz Sur 728',
    lat: 25.671199995871262,
    lng: -100.32695997521606,
    imagen: 'anuncio8.jpg',
    publicado: 1,
    precioId: 6,
    categoriaId: 3,
    usuarioId: 2,
    verificado: 1,
    estado: 'Nuevo León',
    municipio: 'Monterrey',
    tipoId: 3
  },
  {
    titulo: 'Casa minimalista con piscina',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Calle Narciso Serrada de Sevilla',
    lat: 27.39137499755461,
    lng: -99.53632119185244,
    imagen: 'anuncio9.jpg',
    publicado: 1,
    precioId: 4,
    categoriaId: 2,
    usuarioId: 2,
    verificado: 0,
    estado: 'Tamaulipas',
    municipio: 'Nuevo Laredo',
    tipoId: 2
  },
  {
    titulo: 'Lujosa Casa',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Calle Perla 7233',
    lat: 31.679649982452233,
    lng: -106.48518002894016,
    imagen: 'anuncio10.jpg',
    publicado: 1,
    precioId: 3,
    categoriaId: 2,
    usuarioId: 2,
    verificado: 1,
    estado: 'Chihuahua',
    municipio: 'Juárez',
    tipoId: 1
  },
  {
    titulo: 'Bonita Casa de Campo',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Calle Irrigación',
    lat: 19.316377170700402,
    lng: -97.91695619451659,
    imagen: 'anuncio11.jpg',
    publicado: 1,
    precioId: 6,
    categoriaId: 2,
    usuarioId: 3,
    verificado: 0,
    estado: 'Tlaxcala',
    municipio: 'Huamantla',
    tipoId: 3
  },
  {
    titulo: 'Departamento de lujo',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Calle Benito Juárez 12411',
    lat: 32.48235999722144,
    lng: -116.98564996802511,
    imagen: 'anuncio12.jpg',
    publicado: 1,
    precioId: 6,
    categoriaId: 3,
    usuarioId: 3,
    verificado: 1,
    estado: 'Baja California',
    municipio: 'Tijuana',
    tipoId: 2
  },
  {
    titulo: 'Bonito Departamento',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Boulevard Villa del Encanto',
    lat: 24.10249986519349,
    lng: -110.32803427945001,
    imagen: 'anuncio13.jpg',
    publicado: 1,
    precioId: 7,
    categoriaId: 3,
    usuarioId: 3,
    verificado: 0,
    estado: 'Baja California Sur',
    municipio: 'La Paz',
    tipoId: 1
  },
  {
    titulo: 'Casa Residencial Minimalista',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'San Miguel 408',
    lat: 32.440349982325145,
    lng: -114.80744998660286,
    imagen: 'anuncio14.jpg',
    publicado: 1,
    precioId: 9,
    categoriaId: 2,
    usuarioId: 3,
    verificado: 1,
    estado: 'Sonora',
    municipio: 'San Luis Río Colorado',
    tipoId: 3
  },
  {
    titulo: 'Hermoso y Lujoso Departamento',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Obrero Mundial 195',
    lat: 19.401120007690565,
    lng: -99.16284002324699,
    imagen: 'anuncio15.jpg',
    publicado: 1,
    precioId: 8,
    categoriaId: 3,
    usuarioId: 3,
    verificado: 0,
    estado: 'Ciudad de México',
    municipio: 'Benito Juárez',
    tipoId: 2
  },
  {
    titulo: 'Excelente Departamento',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Avenida Estado de México 140C',
    lat: 19.250340005033806,
    lng: -99.60775001887593,
    imagen: 'anuncio16.jpg',
    publicado: 1,
    precioId: 7,
    categoriaId: 3,
    usuarioId: 4,
    verificado: 1,
    estado: 'México',
    municipio: 'Metepec',
    tipoId: 1
  },
  {
    titulo: 'Pequeña Casa de Campo',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Calle Artillería Oriente 12A',
    lat: 19.431739980090285,
    lng: -100.35973003150883,
    imagen: 'anuncio17.jpg',
    publicado: 1,
    precioId: 8,
    categoriaId: 2,
    usuarioId: 4,
    verificado: 0,
    estado: 'Michoacán de Ocampo',
    municipio: 'Zitácuaro',
    tipoId: 3
  },
  {
    titulo: 'Departamento con Terraza',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Avenida Central Oriente',
    lat: 16.751268943821614,
    lng: -93.10105353462228,
    imagen: 'anuncio18.jpg',
    publicado: 1,
    precioId: 10,
    categoriaId: 3,
    usuarioId: 4,
    verificado: 1,
    estado: 'Chiapas',
    municipio: 'Tuxtla Gutiérrez',
    tipoId: 2
  },
  {
    titulo: 'Departamento Minimalista',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Calle 42 Sur',
    lat: 20.92058226415684,
    lng: -89.60443061137536,
    imagen: 'anuncio19.jpg',
    publicado: 1,
    precioId: 7,
    categoriaId: 3,
    usuarioId: 4,
    verificado: 0,
    estado: 'Yucatán',
    municipio: 'Mérida',
    tipoId: 1
  },
  {
    titulo: 'Bonito Departamento',
    descripcion: 'Casa habitación desarrollada en dos niveles de piso terminado, desplantada sobre un lote de terreno de posición medianero conun frente a calle, de topografía visiblemente plana, forma regular.',
    habitaciones: 3,
    estacionamiento: 2,
    wc: 3,
    calle: 'Avenida General Juan Carrasco',
    lat: 23.213532950838353,
    lng: -106.41613785204946,
    imagen: 'anuncio20.jpg',
    publicado: 1,
    precioId: 8,
    categoriaId: 3,
    usuarioId: 4,
    verificado: 1,
    estado: 'Sinaloa',
    municipio: 'Mazatlán',
    tipoId: 3
  },
]

export default propiedades;